### ISSUE TITLE
Configuration issues

### ISSUE THREAD

**Issue by sunxia233** [yorkeyao/VehicleX#2]
Thank you for sharing everything. When I followed the steps and started executing the python Inf.py command, I had a problem:
I saw the unity interface, but

     "The Unity environment took too long to respond. Make sure that: \ n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that:
The environment does not need user interaction to launch
The Academy's Broadcast Hub is configured correctly
The Agents are linked to the appropriate Brains
The environment and the Python interface have compatible versions.

I installed the corresponding version of the package according to your instructions. But now I don't know where the problem lies? Am I not starting the X server and loading the glx module? The problem is that I checked some information and I do n’t know how to start it and how to debug

**Comment by sunxia233** [comment]
When Unity is opened, an interface will be stuck. This is the system will ask you to choose to force exit or wait. I clicked three times to wait, its work. ：）But I encountered another problem
1 3314 270.75420217183887 0.6877099167881646 43.61045176472462 4.167346650508461 0.9784139464509725 4.916606307419233 41
Traceback (most recent call last):
   File "Inference.py", line 116, in <module>
     Get_Save_images_by_attributes (attribute_list, i)
   File "Inference.py", line 79, in Get_Save_images_by_attributes
     if angle [z]> 360:
IndexError: index 3471 is out of bounds for axis 0 with size 3471

I used the provided_imgs_300 you provided as the background image. I use linux system, so the VehicleX.x86_64 under Build-linux is executed. I wonder if I need to modify any other parameters

**Comment by yorkeyao** [comment]
Sorry about this, the first question is because I perform several pre-processing which takes a lot of time. If they cannot be finished on time this bug happens. Directly using better hardware will solve this problem and I will optimize these preprocessing in future updates. The second issue is a bug and I have fixed it in Inference.py.

**Comment by sunxia233** [comment]
Thanks ,It work!Another question, what is the difference between training and inference mode? I tried running the training mode and found that this could take quite a long time. Also I wonder if the code for calculating the FID will be released?

**Comment by yorkeyao** [comment]
1) The difference between training and inference mode is mainly about background and distractors. In training mode, the background is a completely black image and no distractors included.  In inference mode, we use some real images as background and some distractors.
2) Currently, we only released the inference code.  The training code is coming soon.

**Comment by weilli** [comment]
> Thank you for sharing everything. When I followed the steps and started executing the python Inf.py command, I had a problem: I saw the unity interface, but
> 
>      "The Unity environment took too long to respond. Make sure that: \ n" mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that: The environment does not need user interaction to launch The Academy's Broadcast Hub is configured correctly The Agents are linked to the appropriate Brains The environment and the Python interface have compatible versions.
> 
> I installed the corresponding version of the package according to your instructions. But now I don't know where the problem lies? Am I not starting the X server and loading the glx module? The problem is that I checked some information and I do n’t know how to start it and how to debug

I also met this problem. Would you mind giving me some advice to solve it? Thanks!

**Comment by yorkeyao** [comment]
Hi Weilli,

I think there is an similar issue on the GitHub. Sometime this issue will simply happen if your computer is not powerful enough. I think you may need to have at least 1050ti or better to run this app.

Regards,
Yue.

发件人: ***@***.***>
发送时间: 2021年11月27日 0:58
收件人: ***@***.***>
抄送: Yue ***@***.***>; State ***@***.***>
主题: Re: [yorkeyao/VehicleX] Configuration issues (#2)


Thank you for sharing everything. When I followed the steps and started executing the python Inf.py command, I had a problem: I saw the unity interface, but

     "The Unity environment took too long to respond. Make sure that: \ n" mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that: The environment does not need user interaction to launch The Academy's Broadcast Hub is configured correctly The Agents are linked to the appropriate Brains The environment and the Python interface have compatible versions.

I installed the corresponding version of the package according to your instructions. But now I don't know where the problem lies? Am I not starting the X server and loading the glx module? The problem is that I checked some information and I do n’t know how to start it and how to debug

I also met this problem. Would you mind giving me some advice to solve it? Thanks!

―
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyorkeyao%2FVehicleX%2Fissues%2F2%23issuecomment-979996730&data=04%7C01%7Cyue.yao%40anu.edu.au%7Cf9251f3c971640d5bb3108d9b0e4cb71%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C637735318984307619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BuvH3pdU%2FuLD1LYov9ucldlSTsWHJiaT523sfXPcZq4%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFY6EEVOHTOP2FWTWSW5JUTUN6G7LANCNFSM4KF3V2JA&data=04%7C01%7Cyue.yao%40anu.edu.au%7Cf9251f3c971640d5bb3108d9b0e4cb71%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C637735318984317576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WdK%2FR2HmaXfrkCxqkTc2uWGgP53WIkaPuuSSv4ndHYU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cyue.yao%40anu.edu.au%7Cf9251f3c971640d5bb3108d9b0e4cb71%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C637735318984317576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NCoe6lQWhbLQKnIKV8OGeJvzkx3jsUzvUMi0Hp9OCmo%3D&reserved=0> or Android<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cyue.yao%40anu.edu.au%7Cf9251f3c971640d5bb3108d9b0e4cb71%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C637735318984317576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PEj%2F8E5lNn5O73ZzZIKNDBPXx4oeVs%2FoIvbNqp8x0nc%3D&reserved=0>.
